baseURL: "https://joat.me/parlons/"
languageCode: "en-ca"
title: Parlons London
theme: hyde
Menus:
  main:
    - Name: "À propos de nous / About Us"
      Url: "/about"
    - Name: "Contactez nous / Contact us"
      Url: "/page/contact"
    - Name: "Learning French"
      Url: "/page/ressources"
params:
  description: "Un groupe de conversation en français à London, Ontario, Canada"
  layoutReverse: false
  
