baseURL: "https://parlonslondon.ca/"
languageCode: "en-ca"
title: Parlons London
theme: hyde
Menus:
  main:
    - Name: "À propos de nous / About Us"
      Url: "/about"
    - Name: "Learning French"
      Url: "/page/ressources"
params:
  description: "Un groupe de conversation en français à London, Ontario, Canada"
  shortdescription: "Conversation en français à London, Ontario"
  layoutReverse: false
  copyright: CC BY-SA 3.0
