baseURL: "https://parlonslondon.ca/"
languageCode: "en-ca"
title: Parlons London
theme: hyde
Menus:
  main:
    - Name: "Tous les posts / All Posts"
      Url: "/post/"
    - Name: "À propos de nous / About Us"
      Url: "/about"
      Weight: 100
    - Name: "French Resources"
      Url: "/page/ressources"
      Weight: 50
params:
  description_fr: "Un groupe de conversation en français à London, Ontario, Canada"
  description_en: "A French conversation group in London, Ontario, Canada"
  # there's no short English description
  shortdescription_fr: "Groupe de français à London, Ontario"
  layoutReverse: false
  copyright: CC BY-SA 3.0
