#!/bin/bash

msg="$*"

if [ -z "$msg" ]; then
    echo $0: need a commit message
    exit 1
fi

set -e

# build the site
./build

(
    cd public
    git add .
    git commit -m "$msg"
    git push origin master
)

git add .
git commit -m "$msg"
git push
