#!/bin/bash
# create a new post for the next in-person meeting, build and commit the site, then commit the meeting source
# file and the latest site submodule commit (in public)

# Holy Race Conditions, Batman! Just don't run this at midnight on Friday or Saturday, OK?
post_date=$(date --iso-8601=seconds)
expiry_date=$(date --iso-8601=seconds --date='16:30 next sat + 7 days')
text_fr=$(date --date='14:30 next sat' +"Samedi %Y-%m-%d %Hh%M heure de l'Est")
text_en=$(date --date='14:30 next sat' +"Saturday %Y-%m-%d %I:%M %p Eastern")
post_filename="content/meeting/$(date --date='14:30 next sat' +'%Y-%m-%d').md"
meeting_page_filename="content/page/reunion.md"
mtg_url='https://www.meetup.com/French-Conversation-in-London'

# delete previous meeting(s)
echo Removing previous meetings:
rm -fv content/meeting/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].md

cat >"${post_filename}" <<POST
---
title: "Prochaine réunion / Upcoming meeting"
date: ${post_date}
expiryDate: ${expiry_date}
draft: false
---

Notre prochaine réunion en personne / _Our next in-person meeting_

Notez bien, pour l'instant il n'y a pas de réunion en ligne / _Please note, for now there is no online meeting this week_

Heure / Time
: ${text_fr}  
  _${text_en}_

URL
: ${mtg_url}

<!--more-->

Nous espérons vous voir là-bas! / _Hope to see you there!_

We have some beginners, lots of intermediate-level, and some advanced/expert-level speakers. We help each other learn while enjoying good conversations! We have met every Saturday since July 2012. Please read [this](/about/) before attending.
POST

cp "${post_filename}" "${meeting_page_filename}"
