#!/bin/bash
# create a new post for the next Saturday meeting, build and commit the site, then commit the meeting source
# file and the latest site submodule commit (in public)

# Holy Race Conditions, Batman! Just don't run this at midnight on Friday or Saturday, OK?
post_date=$(date --iso-8601=seconds)
text_fr=$(date --date='14:30 next sat' +"Samedi %Y-%m-%d %Hh%M heure de l'Est")
text_en=$(date --date='14:30 next sat' +"Saturday %Y-%m-%d %I:%M %p Eastern")
post_filename="content/meeting/$(date --date='14:30 next sat' +'%Y-%m-%d').md"

cat >"${post_filename}" <<POST
---
title: "Prochaine réunion / Next meeting"
date: ${post_date}
draft: false
---

Notre prochaine réunion en ligne / _Our next online meeting_

Heure / Time
: ${text_fr}  
  _${text_en}_

URL
: https://westernuniversity.zoom.us/j/96489379313?pwd=SGJqdStYNUN5K2wzSEFxVmoxT3luUT09

<!--more-->

Nous espérons vous voir là-bas! / _Hope to see you there!_
POST

./build

echo '**** committing public'
pushd public
git add .
git commit -m "automatic addition of next meeting"
git push
popd

echo '**** committing source'
git add public "${post_filename}"
git commit public "${post_filename}" -m "automatic addition of next meeting"
git push
